url: "https://nnlk05.github.io"
baseurl: "/blog"

title: "NNlk05's Venting Hole"
description: "Otherwise known as my personal blog."
author: "NNlk05"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
kramdown:
  input: GFM
  toc_levels: 1..6
  auto_ids: true
  extensions: [theme_implicit_ids, footnotes]
